pub mod audit;
pub mod canon_jcs;
pub mod digest;
pub mod engine;
pub mod errors;
pub mod evidence;
pub mod manifest;
pub mod operator_registry;
pub mod operators;
pub mod program;
pub mod rd;
pub mod replay;
pub mod schema_validate;
pub mod state;
pub mod tie_break;
pub mod trace;
pub mod types;
pub mod uir;

pub use audit::{verify_ledger_head, LedgerEntry};
pub use canon_jcs::{canonicalize_jcs, canonicalize_with_rd};
pub use digest::digest_sha256_jcs;
pub use engine::Engine;
pub use errors::CoreError;
pub use evidence::{build_evidence, Evidence, EvidenceStep};
pub use manifest::{build_manifest, ReplayManifest};
pub use operator_registry::OperatorRegistry;
pub use operators::{EngineOperator, OperatorRole};
pub use program::Program;
pub use rd::{CanonSettings, FloatPolicy, RunDescriptor, SeedPolicy};
pub use replay::{first_divergence, verify_manifest_consistency, FirstDivergence};
pub use schema_validate::validate_against_schema;
pub use state::init_sigma_from_uir;
pub use tie_break::sort_by_score_then_digest;
pub use trace::{EngineTrace, TraceEntry};
pub use types::{Digest, Manifest, ScoredValue, Sigma, Trace, TraceStep};
pub use uir::{EdgeType, NodeType, UirEdge, UirGraph, UirNode};
